CREATE TABLE projeto(
    NAME VARCHAR(100),
    STATUS INT NOT NULL,
    ENABLED INT NOT NULL,
    VIEW_STATE INT NOT NULL,
    ACCESS_MIN INT NOT NULL,
    DESCRIPTION VARCHAR(240),
    CATEGORY_ID INT NOT NULL,
    INHERIT_GLOBAL INT NOT NULL,
    PRIMARY KEY (NAME)
);