CREATE TABLE usuario(
    USERNAME VARCHAR(240),
    REALNAME VARCHAR(240),
    EMAIL VARCHAR(240),
    ENABLED INT NOT NULL,
    PROTECTED INT NOT NULL,
    ACCESS_LEVEL INT NOT NULL,
    COOKIE_STRING VARCHAR(100),
    TIPO_USUARIO VARCHAR(240),
    PRIMARY KEY (USERNAME)
);